ponomarev.alexander/hw7
PonomarevAlexxander/tinkoff-academy-tasks pull request #10
Opened 2023-11-26 17:56 UTC by PonomarevAlexxander

2023-11-27 13:27 UTC, nexen505 requested changes

2023-11-27 13:27 UTC, nexen505 commented on src/main/java/edu/hw7/task1/AtomicExample.java
> +        List<Thread> threads = Stream.generate(() -> new Thread(COUNTER::incrementAndGet))
Проблема: такой подход приводит к необходимости ручного управления потоками.

Предложение: изменить реализацию на использование `Executors#newFixedThreadPool`.

2023-11-27 13:27 UTC, nexen505 commented on src/main/java/edu/hw7/task2/Factorial.java
> +        return IntStream
Проблема: по заданию должен быть использован параллельный поток.

Предложение: привести реализацию в соответствие с заданием.

2023-11-27 13:27 UTC, nexen505 commented on src/main/java/edu/hw7/task3/ReadWritePersonDatabase.java
> +    public synchronized void add(Person person) {
Проблема: так все операции синхронизированы между собой и блокировка на запись и чтение бесполезна.

Предложение: тут и далее уйти от `synchronized`.

2023-11-27 16:31 UTC, PonomarevAlexxander commented on src/main/java/edu/hw7/task3/ReadWritePersonDatabase.java
> +    public synchronized void add(Person person) {
забыл убрать(

2023-11-28 14:04 UTC, nexen505 requested changes

2023-11-28 14:04 UTC, nexen505 commented on src/main/java/edu/hw7/task1/AtomicExample.java
> +                CompletableFuture.runAsync(COUNTER::incrementAndGet, executor).join();
Проблема: в таком виде из-за `join` задачи будут запускаться по очереди, а не параллельно.

Предложение: не дожидаться результата запущенной задачи, так как это сделает метод `ExecutorService#close`.

2023-11-29 08:07 UTC, nexen505 approved these changes

2023-11-29 08:17 UTC, merged