ponomarev.alexander/hw8
PonomarevAlexxander/tinkoff-academy-tasks pull request #11
Opened 2023-12-03 19:43 UTC by PonomarevAlexxander

2023-12-04 13:47 UTC, nexen505 requested changes

2023-12-04 13:47 UTC, nexen505 commented on src/test/java/edu/hw8/task1/SocketServerTest.java
> +        Thread.sleep(1000);
Мысль: если хочется дождаться старта, лучше воспользоваться многопоточным примитивом `CountDownLatch`.

2023-12-04 13:47 UTC, nexen505 commented on src/main/java/edu/hw8/task1/SocketServer.java
> +        try (ServerSocket server = new ServerSocket(port);
Проблема: в таком виде сервер неудобно закрывать.

Предложение: реализовать интерфейс `AutoCloseable`, в котором будет осуществляться закрытие серверного сокета.

2023-12-04 13:47 UTC, nexen505 commented on src/main/java/edu/hw8/task1/SocketServer.java
> +                    Socket clientSocket = server.accept();
Проблема: ресурс не закрывается.

Предложение: учесть в реализации необходимость закрыть сокет.

2023-12-04 13:47 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +                    threads[index] = new Thread(tasks.poll());
Проблема: так потоки будут созданы только с задачами, которые были в очереди на момент старта. Кроме того, очередь задач не будет разобрана воркерами пула.

Предложение: создать потоки так, чтобы они на протяжении жизни пула ожидали задачи из очереди и выполняли их.

2023-12-04 13:47 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +                thread.join();
Проблема: возможна блокировка потока.

Предложение: использовать `java.lang.Thread#join(java.time.Duration)` и прервать поток вручную в случае неудачи в ожидании.

2023-12-08 10:38 UTC, nexen505 requested changes

2023-12-08 10:38 UTC, nexen505 commented on src/test/java/edu/hw8/task1/SocketServerTest.java
> +                    latch.countDown();
Мысль: кажется, надо это делать после запуска сервера.

2023-12-08 10:38 UTC, nexen505 commented on src/test/java/edu/hw8/task1/SocketServerTest.java
> +            latch.await();
Проблема: можно зависнуть.

Предложение: указать таймаут ожидания.

2023-12-08 10:38 UTC, nexen505 commented on src/test/java/edu/hw8/task1/SocketServerTest.java
> +            Thread.sleep(1000);
Предложение: воспользовать механизмом с использованием `CountDownLatch`, как в соседнем тесте.

2023-12-08 10:38 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +                thread.join(timeout);
Проблема: тут не гарантированно, что по окончании `join` поток будет остановлен.

Предложение: воспользоваться методом `Thread#join(Duration)`, который возвращает флаг результата ожидания и прервать поток, если дождаться завершения за выделенное время не удалось.

2023-12-08 10:43 UTC, PonomarevAlexxander commented on src/test/java/edu/hw8/task1/SocketServerTest.java
> +                    latch.countDown();
@nexen505 у нас же запуск функции `start` у сервера уходит в бесконечный цикл и поток фактически блокируется в этом месте, как определить что сервер запустился извне?

2023-12-12 08:39 UTC, nexen505 approved these changes

2023-12-13 17:43 UTC, merged