ponomarev.alexander/project4
PonomarevAlexxander/tinkoff-academy-tasks pull request #12
Opened 2023-12-09 23:03 UTC by PonomarevAlexxander

Complete project with additional tasks:

- colorful images
- gamma-correction
- symmetry
- receive like in [chat](https://t.me/c/1690654462/11356)

2023-12-09 23:06 UTC, PonomarevAlexxander commented
<details><summary>Examples:</summary>
<p>

![изображение](https://github.com/PonomarevAlexxander/tinkoff-academy-tasks/assets/113100755/5e621caf-e0eb-4ca8-a451-69df78b87693)
![изображение](https://github.com/PonomarevAlexxander/tinkoff-academy-tasks/assets/113100755/7d4ed763-6587-4d69-b6a4-ab3f1bfbbbaa)
![изображение](https://github.com/PonomarevAlexxander/tinkoff-academy-tasks/assets/113100755/0262a084-ea47-4034-ab92-9dac4abfd002)
![изображение](https://github.com/PonomarevAlexxander/tinkoff-academy-tasks/assets/113100755/75a9cc6d-26e6-4909-9bec-2266c950fe3e)

</p>
</details>

2023-12-14 10:47 UTC, nexen505 requested changes

2023-12-14 10:47 UTC, nexen505 commented on src/main/java/edu/project4/Main.java
> +        while (affins.size() < 5) {
Косметика:

```java suggestion
        while (affins.size() < colors.size()) {
```

2023-12-14 10:47 UTC, nexen505 commented on src/main/java/edu/project4/generator/ParallelRenderer.java
> +                        feature.get();
Проблема: стрим ленивый - так задачи будут запускаться и ожидаться по одной.

Предложение: просто запускать задачи по счетчику в цикле через `ExecutorService#execute`, а закрытие через `try-with-resources` и так дождется их завершения.

2023-12-14 10:47 UTC, nexen505 commented on src/main/java/edu/project4/generator/ParallelRenderer.java
> +public class ParallelRenderer implements Renderer {
Предложение: провести рефакторинг, чтобы по возможности избежать дублирования кода с `SequentialRenderer`.

2023-12-19 12:19 UTC, nexen505 requested changes

2023-12-19 12:19 UTC, nexen505 commented on src/main/java/edu/project4/generator/ParallelRenderer.java
> +    protected void plot(FractalImage canvas, BoundingRectangle rectangle, Point point, Color affinColor) {
Проблема: введение такого метода наряду с реализациями значительно усложняет логику и понимание кода.

Предложение: сделать класс `Pixel` мутабельным и потокобезопасным, что поможет избежать лишней синхронизации при преобразованиях. При таком изменении метод `plot` будет иметь одинаковую реализацию в однопоточном и многопоточном режимах.

2023-12-19 12:19 UTC, nexen505 commented on src/main/java/edu/project4/generator/ParallelRenderer.java
> +            pixel = updatePixel(pixel, affinColor);
Мысль: вдогонку к соображению выше, метод `updatePixel` может быть нестатическим методом `Point`.

2023-12-20 08:41 UTC, PonomarevAlexxander commented on src/main/java/edu/project4/generator/ParallelRenderer.java
> +            pixel = updatePixel(pixel, affinColor);
Я думал об этом, но решил, что реализация изменения цветов и тд может быть разная (в статье про пламя написаны разные методы) и фактически не очень относится именно к `Point` или `Pixel`, поэтому решил сделать это частью логики `Renderer`

2023-12-22 04:36 UTC, nexen505 commented on src/main/java/edu/project4/generator/ParallelRenderer.java
> +            pixel = updatePixel(pixel, affinColor);
Фактически по коду оно относится именно к `Pixel`, так как его состояние меняется по цвету.

2023-12-22 04:37 UTC, nexen505 commented on src/main/java/edu/project4/generator/Renderer.java
> +    protected void updatePixelColor(Pixel pixel, Color affinColor) {
Проблема: возможна гонка на состоянии пикселя.

Предложение: либо сделать весь этот метод синхронизированным методом `Pixel`, либо синхронизировать его целиком тут на экземпляре `Pixel`.

2023-12-22 04:38 UTC, nexen505 approved these changes

2023-12-22 15:37 UTC, PonomarevAlexxander commented on src/main/java/edu/project4/generator/Renderer.java
> +    protected void updatePixelColor(Pixel pixel, Color affinColor) {
Да, согласен  
Я когда об этом думал решил что там изменения с синхронизацией целиком и без будут идентичными, но сейчас понял, что если один поток поменяет цвет, а другой в этот момент уже использует старый цвет, то изменения первого будут не использованы

2023-12-22 15:44 UTC, PonomarevAlexxander commented
@nexen505 можете посмотреть? сейчас должно быть ок

2023-12-25 13:16 UTC, merged