Complete hw9
PonomarevAlexxander/tinkoff-academy-tasks pull request #13
Opened 2023-12-10 21:00 UTC by PonomarevAlexxander

2023-12-10 21:08 UTC, PonomarevAlexxander commented
![изображение](https://github.com/PonomarevAlexxander/tinkoff-academy-tasks/assets/113100755/ffd50bb0-533d-43ce-bb21-d75071bedd04)
![изображение](https://github.com/PonomarevAlexxander/tinkoff-academy-tasks/assets/113100755/322f0291-495b-4ba4-8e1e-a154a31262dd)
![c1004aab4f072c0c666e5275cd8ed087](https://github.com/PonomarevAlexxander/tinkoff-academy-tasks/assets/113100755/c86c2047-7439-4b4b-9e36-1726ee6618ea)

2023-12-12 11:50 UTC, nexen505 requested changes

2023-12-12 11:50 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +public class StatsCollector {
Проблема: кажется, суть задания неверно понята.

Предложение: инкапсулировать логику записи и расчета метрик. Клиент пишет метрику -> коллектор кладет в пул задачу на вычисление метрики -> в фоновом режиме происходит расчет и сохранение результатов расчета -> клиент всегда может читать текущий слепок статистики всех метрик.

2023-12-12 11:50 UTC, nexen505 commented on src/main/java/edu/hw9/task2/FileUtils.java
> +             Stream<Path> tree = Files.walk(directory)) {
Мысль: есть ощущение, что можно это не итерировать, так как это можно сделать внутри `FilesCounter`.

2023-12-13 20:34 UTC, PonomarevAlexxander commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +public class StatsCollector {
@nexen505 Да, я не до конца понял принцип. Получается что статистика общая? То есть все клиенты добавляют данные к уже существующим? или перезаписывают их?

2023-12-18 12:34 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +public class StatsCollector {
Статистика общая: клиенты могут писать данные по одним и тем же метрикам, что должно рассчитывать объединенную статистику.

2023-12-18 12:37 UTC, nexen505 requested changes

2023-12-18 12:37 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +                        (oldValue, value) -> (oldValue * dataSize.addAndGet(length) + value) / dataSize.get()
Проблема: в функции есть сайд-эффект, который может выполниться несколько раз при гонке на ключе.

Предложение: для среднего хранить в мапе количество элементов.

2023-12-18 12:37 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +                    statistics.merge(metric.name(), min.getAsDouble(), Double::max);
Проблема: опечатка.

```java suggestion
                    statistics.merge(metric.name(), min.getAsDouble(), Double::min);
```

Предложение: написать тесты так, чтобы ее можно было отловить.

2023-12-19 08:12 UTC, PonomarevAlexxander commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +                        (oldValue, value) -> (oldValue * dataSize.addAndGet(length) + value) / dataSize.get()
мне казалось что merge атомарная операция, где там может быть сайд эффект? учитывая что `dataSize` только для `average` используется

2023-12-19 08:45 UTC, PonomarevAlexxander commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +                        (oldValue, value) -> (oldValue * dataSize.addAndGet(length) + value) / dataSize.get()
вроде пофиксил, добавил синхронизацию, тк в любом случае будет получатся что потоки которые хотят посчитать average будут выполняться последовательно

2023-12-19 11:18 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +                        (oldValue, value) -> (oldValue * dataSize.addAndGet(length) + value) / dataSize.get()
`merge` атомарная, но если ключ редактировался конкурентно, то функция слияния результатов может выполниться несколько раз.

2023-12-19 11:53 UTC, merged