Complete hw11
PonomarevAlexxander/tinkoff-academy-tasks pull request #16
Opened 2023-12-17 20:59 UTC by PonomarevAlexxander

2023-12-18 00:28 UTC, PonomarevAlexxander commented
Я честно не понимаю почему оно падает, тк локально все проходит(
![изображение](https://github.com/PonomarevAlexxander/tinkoff-academy-tasks/assets/113100755/353c2b6b-8d9f-4765-9a89-c659e84faf8a)

2023-12-22 10:53 UTC, nexen505 commented
По тестам предлагаю тогда их пометить `@Disabled`.

2023-12-22 10:53 UTC, nexen505 requested changes

2023-12-22 10:53 UTC, nexen505 commented on src/test/java/edu/hw11/task1/HelloBuddyTest.java
> +            .method(named("toString")).intercept(FixedValue.value("Hello, ByteBuddy!"))
Проблема: матчить по имени `toString` мало, так как нужно учитывать аргументы и тип возвращаемого значения.

Предложение: использовать `net.bytebuddy.matcher.ElementMatchers#isToString`

2023-12-23 16:11 UTC, nexen505 approved these changes

2023-12-25 13:15 UTC, merged