ponomarev.alexander/hw2
PonomarevAlexxander/tinkoff-academy-tasks pull request #2
Opened 2023-10-18 20:48 UTC by PonomarevAlexxander

All tasks comleted
_____________
<sub>Анекдот:  
Еврейский SQL отвечает запросом на запрос</sub>

2023-10-20 06:37 UTC, nexen505 requested changes

2023-10-20 06:37 UTC, nexen505 commented on src/main/java/edu/hw2/task2/BoundingRectangle.java
> +public abstract class BoundingRectangle {
Проблема: по заданию методы `setWidth`/`setHeight` должны быть.

Предложение: привести реализацию в соответствие с требованиями.

2023-10-20 06:37 UTC, nexen505 commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +        while (true) {
Проблема: такой цикл повышает вероятность ошибки при изменениях и приведет к зацикливанию.

Предложение: можно условие завязать на проверку количества попыток в сравнении с максимально допустимым.

2023-10-20 06:37 UTC, nexen505 commented on src/test/java/edu/hw2/task3/PopularCommandExecutorTest.java
> +class PopularCommandExecutorTest {
Предложение: расширить набор тестов тестами и других добавленных классов.

2023-10-20 06:37 UTC, nexen505 commented on src/main/java/edu/hw2/task3/DefaultConnectionManager.java
> +        if (Math.random() < PROBABILITY) {
Проблема: такую реализацию сложно тестировать, так как надо внедрять в моки статического метода.

Предложение: использовать конструктор с экземпляром `java.util.Random`, что и решит проблему тестирования, и позволит реализовать случайность. Эта мысль актуальна и к другим классам задания, где используется случайный фактор.

2023-10-20 07:55 UTC, PonomarevAlexxander commented on src/main/java/edu/hw2/task2/BoundingRectangle.java
> +public abstract class BoundingRectangle {
@nexen505  Там не сказано где именно они должны быть, я же могу их добавить в класс `Rectangle `и `Square`, но не в базовый? Плюс в самом задании я не нашел что в переработке должны быть эти методы. То есть понятие высоты/ширины у меня присутствует но нет возможности изменять состояние обьекта
![изображение](https://github.com/PonomarevAlexxander/tinkoff-academy-tasks/assets/113100755/7f1b1d68-44c6-445d-9f44-466e00d4048a)

2023-10-23 14:16 UTC, nexen505 requested changes

2023-10-23 14:16 UTC, nexen505 commented on src/test/java/edu/hw2/task3/FaultyConnectionTest.java
> +        } catch (Exception ignored) {
Косметика: тут и в других подобных местах добавлены блоки `catch`, которые не нужны.

2023-10-23 14:16 UTC, nexen505 commented on src/test/java/edu/hw2/task3/FaultyConnectionTest.java
> +                return SUCCESS_PROBABILITY;
Предложение: разбить тест на два для разных значений.

2023-10-23 14:16 UTC, nexen505 commented on src/test/java/edu/hw2/task2/BoundingRectangleTest.java
> +            .isEqualTo(area / obj.getHeight() * newHeight);
Проблема: тест завязан на логику реализации - он не проверяет ожидаемый результат.

Предложение: использовать только входные параметры теста без доп.логики - получили данные, запустили метод, проверили выходное значение на соответствие ожидаемому.

2023-10-27 08:42 UTC, nexen505 approved these changes

2023-10-27 09:33 UTC, merged