ponomarev.alexander/hw3
PonomarevAlexxander/tinkoff-academy-tasks pull request #4
Opened 2023-10-25 22:32 UTC by PonomarevAlexxander

All tasks completed

2023-10-31 12:45 UTC, nexen505 requested changes

2023-10-31 12:45 UTC, nexen505 commented on src/main/java/edu/hw3/task3/FrequencyDictionary.java
> +            frequency.put(object, currentFreq);
Проблема: конструкция чтение+запись неатомарна и сложна для восприятия.

Предложение: использовать метод `java.util.Map#merge`

2023-10-31 12:45 UTC, nexen505 commented on src/main/java/edu/hw3/task5/Contacts.java
> +    public static List<Object> parseContacts(List<String> contacts, String compareFormat) {
Проблема: в задании под объектами подразумевались `record` с фамилией и именем.

Предложение: в реализации сначала провести парсинг списка строк в список объектов, а затем отсортировать их.

2023-10-31 12:45 UTC, nexen505 commented on src/main/java/edu/hw3/task6/Stock.java
> +public record Stock(int price) implements Comparable<Stock> {
Косметика: семантически у акции обычно есть еще и тикер, кроме цены.

2023-11-01 21:10 UTC, PonomarevAlexxander commented on src/main/java/edu/hw3/task5/Contacts.java
> +    public static List<Object> parseContacts(List<String> contacts, String compareFormat) {
Я слишком буквально воспринял задание)

2023-11-03 05:13 UTC, nexen505 approved these changes

2023-11-03 07:18 UTC, merged