ponomarev.alexander/hw6
PonomarevAlexxander/tinkoff-academy-tasks pull request #8
Opened 2023-11-19 00:40 UTC by PonomarevAlexxander

2023-11-20 14:28 UTC, nexen505 requested changes

2023-11-20 14:28 UTC, nexen505 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +    public void mergeDataFrom(Path file) throws IOException {
Проблема: методы записи или чтения не встроены в логику реализации интерфейса `Map`.

Предложение: вызывать их внутри соответствующих операций.

2023-11-20 14:28 UTC, nexen505 commented on src/main/java/edu/hw6/task5/HackerNews.java
> +        HttpClient client = HttpClient.newHttpClient();
Проблема: тут и в других местах ресурс не закрывается.

Предложение: поместить его в `try-with-resources`.

2023-11-21 20:07 UTC, PonomarevAlexxander commented on src/main/java/edu/hw6/task1/DiskMap.java
> +    public void mergeDataFrom(Path file) throws IOException {
@nexen505 Я думал так сделать, но потом решил что это будет очень затратно и сделал мапу `AutoClosable` (что конечно тоже не очень интуитивно) и в `close()` поместил выгрузку в файл.  
Почему здесь стоит встроить эту логику в операции? Или может надо было изначально по другому делать :/

2023-11-23 13:25 UTC, nexen505 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +    public void mergeDataFrom(Path file) throws IOException {
На самом деле, тут это момент дискуссионный относительно задания, но текущий вариант мне больше нравится с точки зрения консистентности данных.

2023-11-23 13:26 UTC, nexen505 requested changes

2023-11-23 13:26 UTC, nexen505 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +    private void load() {
Проблема: если мы хотим обеспечить консистентность, то проглатывать тут и в других местах `IOException` неправильно, так как пользователь при проблемах ничего о них не узнает.

Предложение: пробрасывать его, оборачивая, например в `IllegalStateException`.

2023-11-27 13:47 UTC, nexen505 approved these changes

2023-11-27 16:29 UTC, merged