ponomarev.alexnder/project3
PonomarevAlexxander/tinkoff-academy-tasks pull request #9
Opened 2023-11-19 19:08 UTC by PonomarevAlexxander

Project completed. Two special analytics added.

2023-11-22 13:17 UTC, nexen505 requested changes

2023-11-22 13:17 UTC, nexen505 commented on src/main/java/edu/project3/LogsAnalyzer.java
> +    public Map<Integer, Long> getStatusCodeFrequency() {
Проблема: по заданию надо выбрать самые часто встречающиеся, а здесь используется лишь количество, и использовать метод в отчете.

Предложение: привести реализацию в соответствие с заданием.

2023-11-22 13:17 UTC, nexen505 commented on src/main/java/edu/project3/FilesLogsProvider.java
> +                return null;
Проблема: исключение проглатывается и пользователю дается риск `NullPointerException`.

Предложение: пробрасывать исключение.

2023-11-22 13:17 UTC, nexen505 commented on src/main/java/edu/project3/HttpLogsProvider.java
> +        HttpClient client = HttpClient.newHttpClient();
Проблема: ресурс не закрывается.

Предложение: использовать `try-with-resources`.

2023-11-22 13:17 UTC, nexen505 commented on src/main/java/edu/project3/LogsAnalyzer.java
> +    public Map<String, Long> getMostFrequentResources(int firstN) {
Проблема: метод не используется в отчете.

Предложение: добавить в отчет эту информацию.

2023-11-22 13:17 UTC, nexen505 commented on src/main/java/edu/project3/Main.java
> +    public static void main(String[] args) {
Проблема: метод довольно большой, что усложняет разработку и восприятие.

Предложение: декомпозировать его на отдельные приватные методы.

2023-11-28 13:20 UTC, nexen505 requested changes

2023-11-28 13:20 UTC, nexen505 commented on src/main/java/edu/project3/HttpLogsProvider.java
> +            try (HttpClient client = HttpClient.newHttpClient()) {
Проблема: клиент открывается на каждый адрес, что излишне расходует ресурсы.

Предложение: создать клиент вне цикла один раз и переиспользовать этот единственный экземпляр внутри цикла.

2023-11-28 13:20 UTC, nexen505 commented on src/main/java/edu/project3/Main.java
> +    public static void main(String[] args) {
Мысль по-прежнему актуальна.

2023-11-28 13:20 UTC, nexen505 commented on src/test/java/edu/project3/FilesLogsProviderTest.java
> +    private static final Path TEST_FILE = Path.of("logs.txt");
Проблема: такой способ создания файла в тесте требует ручного контроля его жизненного цикла.

Предложение: воспользоваться механизмом временных файлов JUnit (например, https://www.baeldung.com/junit-5-temporary-directory)

2023-11-29 08:17 UTC, nexen505 approved these changes

2023-11-29 08:22 UTC, PonomarevAlexxander commented
@nexen505 7 баллов потому что были исправления?

2023-11-29 19:58 UTC, merged